import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff0f5',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: '#ad1457',
    paddingTop: Platform.OS === 'ios' ? 0 : 20,
    paddingBottom: 10,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  logo: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  menuIcon: {
    width: 28,
    height: 28,
    tintColor: 'white',
  },
  headerTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    marginHorizontal: 10,
    textAlign: 'center',
  },
  authLinks: {
    flexDirection: 'row',
  },
  loginButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  authButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 12,
  },
  section: {
    backgroundColor: 'white',
    margin: 15,
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  altBg: {
    backgroundColor: '#f8e6ee',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#9f3458',
    marginBottom: 15,
    textAlign: 'center',
  },
  form: {
    marginBottom: 10,
  },
  label: {
    fontSize: 16,
    marginBottom: 5,
    color: '#333',
    fontWeight: '500',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
    fontSize: 16,
    backgroundColor: '#f9f9f9',
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingVertical: 10,
  },
  switchLabel: {
    fontSize: 16,
    color: '#333',
    flex: 1,
  },
  button: {
    backgroundColor: '#9f3458',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 5,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sosButton: {
    backgroundColor: '#ff1744',
    padding: 15,
    borderRadius: 50,
    alignItems: 'center',
    marginTop: 15,
    shadowColor: '#ff1744',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  sosButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  motoristaCard: {
    backgroundColor: '#f8bbd0',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
  },
  motoristaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  motoristaImg: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 10,
  },
  motoristaInfoContainer: {
    flex: 1,
  },
  motoristaNome: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  motoristaInfo: {
    fontSize: 14,
    color: '#555',
  },
  motoristaCarro: {
    fontSize: 14,
    color: '#555',
    marginBottom: 5,
  },
  motoristaPreco: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#9f3458',
    marginBottom: 10,
  },
  emptyText: {
    textAlign: 'center',
    color: '#888',
    fontStyle: 'italic',
    padding: 20,
    fontSize: 16,
  },
  mapButton: {
    backgroundColor: '#9f3458',
    padding: 12,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 15,
    width: 200,
    alignSelf: 'center',
  },
  mapButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
  mapImage: {
    width: '100%',
    height: 200,
    borderRadius: 10,
  },
  statusCard: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#9f3458',
    marginBottom: 10,
  },
  statusText: {
    fontSize: 16,
    color: '#555',
    marginBottom: 10,
    textAlign: 'center',
  },
  timer: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#9f3458',
  },
  contactForm: {
    marginBottom: 20,
  },
  submitButton: {
    backgroundColor: '#9f3458',
    padding: 15,
    borderRadius: 50,
    alignItems: 'center',
    marginTop: 10,
  },
  submitButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  contactInfo: {
    marginTop: 20,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(248, 187, 208, 0.2)',
  },
  contactIcon: {
    width: 30,
    height: 30,
    marginRight: 15,
    tintColor: '#9f3458',
  },
  contactText: {
    fontSize: 16,
    color: '#333',
    flex: 1,
  },
  // Drawer styles
  drawerHeader: {
    padding: 20,
    backgroundColor: '#ad1457',
    alignItems: 'center',
    marginBottom: 10,
  },
  drawerLogo: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 10,
  },
  drawerTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  drawerLabel: {
    fontSize: 16,
    fontWeight: '500',
  },
  drawerFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#ccc',
    marginTop: 20,
  },
  // Notification styles
  notificationContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    left: 10,
    zIndex: 1000,
  },
  notificationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  notificationIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  notificationMessage: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },
  // About screen styles
  aboutContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  reverse: {
    flexDirection: 'row-reverse',
  },
  sectionImage: {
    width: '40%',
    height: 150,
    borderRadius: 10,
    marginRight: 20,
  },
  aboutText: {
    flex: 1,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 24,
    color: '#555',
    marginBottom: 15,
  },
  stats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  statItem: {
    alignItems: 'center',
    backgroundColor: '#f8bbd0',
    padding: 15,
    borderRadius: 10,
    flex: 1,
    marginHorizontal: 5,
  },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#9f3458',
  },
  statLabel: {
    fontSize: 12,
    color: '#555',
    textAlign: 'center',
    marginTop: 5,
  },
  // How it works screen styles
  stepsContainer: {
    marginTop: 20,
  },
  step: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  stepNumber: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#9f3458',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  stepNumberText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#9f3458',
    marginBottom: 5,
    textAlign: 'center',
  },
  stepDescription: {
    fontSize: 14,
    color: '#555',
    textAlign: 'center',
  },
  stepDetails: {
    marginTop: 20,
  },
  stepDetail: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  stepDetailTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#9f3458',
    marginBottom: 15,
    textAlign: 'center',
  },
  stepList: {
    paddingLeft: 15,
  },
  stepListItem: {
    fontSize: 14,
    color: '#555',
    marginBottom: 8,
  },
  // Security screen styles
  securityFeatures: {
    marginTop: 20,
  },
  feature: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  featureIcon: {
    width: 50,
    height: 50,
    marginBottom: 10,
    tintColor: '#9f3458',
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#9f3458',
    marginBottom: 5,
    textAlign: 'center',
  },
  featureDescription: {
    fontSize: 14,
    color: '#555',
    textAlign: 'center',
  },
  policyContent: {
    marginTop: 20,
  },
  policyItem: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  policyTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#9f3458',
    marginBottom: 5,
  },
  policyDescription: {
    fontSize: 14,
    color: '#555',
  },
  // Profile screen styles
  profileInfo: {
    alignItems: 'center',
    marginBottom: 20,
  },
  profileImg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 15,
    borderWidth: 3,
    borderColor: '#9f3458',
  },
  profileName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  profileEmail: {
    fontSize: 16,
    color: '#555',
    marginBottom: 5,
  },
  profileType: {
    fontSize: 16,
    color: '#9f3458',
    fontWeight: '500',
  },
  profileActions: {
    marginTop: 20,
  },
  profileButton: {
    backgroundColor: '#9f3458',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
  },
  profileButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  logoutButton: {
    backgroundColor: '#d32f2f',
  },
  footerText: {
    color: '#555',
    fontSize: 12,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#9f3458',
  },
  closeButton: {
    padding: 6,
  },
  closeButtonText: {
    fontSize: 22,
    color: '#9f3458',
    fontWeight: 'bold',
  },
  sectionSubtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
  },
  gorjetaSection: {
    marginBottom: 15,
  },
  botoesGorjeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  gorjetaButton: {
    flex: 1,
    padding: 12,
    backgroundColor: '#f3e5f5',
    marginHorizontal: 4,
    borderRadius: 8,
    alignItems: 'center',
  },
  gorjetaButtonSelected: {
    backgroundColor: '#9f3458',
  },
  gorjetaButtonText: {
    color: '#9f3458',
    fontWeight: '600',
  },
  personalizadoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  personalizadoInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    marginRight: 10,
  },
  personalizadoButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#9f3458',
    borderRadius: 8,
  },
  personalizadoButtonText: {
    color: 'white',
    fontWeight: '600',
  },
  avaliacaoSection: {
    marginBottom: 15,
  },
  estrelasContainer: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  estrela: {
    fontSize: 32,
    color: '#ccc',
    marginRight: 8,
  },
  estrelaAtiva: {
    color: '#ffb300',
  },
  comentarioInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    minHeight: 80,
  },
  actionButtons: {
    marginTop: 10,
  },
  confirmButton: {
    backgroundColor: '#9f3458',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
  },
  confirmButtonText: {
    color: 'white',
    fontWeight: '700',
  },
  cancelButton: {
    backgroundColor: '#ddd',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#333',
    fontWeight: '600',
  },
  historyCard: {
    backgroundColor: '#f8e6ee',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  historyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#9f3458',
  },
  historyInfo: {
    fontSize: 14,
    color: '#555',
    marginTop: 4,
  },
  historyStatus: {
    fontSize: 14,
    color: '#333',
    marginTop: 6,
    fontWeight: '600',
  },
  // Minor form spacing for SOS contacts
  sosFormRow: {
    marginBottom: 10,
  },
});

